Repository abs-lang/abs, pull requests merged in 2019-02, with the labels that each got.

#151 Allow, destructuring hashes, closes #47
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  object/object.go
Labels: enhancement

#158 added `sleep` function, closes #157
  docs/types/builtin-function.md
  evaluator/evaluator_test.go
  evaluator/functions.go
Labels: enhancement

#159 Contributing guidelines
  CONTRIBUTING.md
  docs/misc/technical-details.md
Labels: documentation

#178 Make it works with wget 1.20.1
  docs/installer.sh
Labels: bug

#182 Better illegal tokens when parsing numbers, closes #176
  lexer/lexer.go
  lexer/lexer_test.go
Labels: bug

#181 Mount the local ABS history inside the dev container, closes #175
  Makefile
Labels: enhancement

#189 number.round(decimals), number.floor(), number.ceil()
  docs/types/number.md
  docs/types/string.md
  evaluator/evaluator_test.go
  evaluator/functions.go
Labels: enhancement

#179 Experimental support for background commands, closes #70
  docs/syntax/system-commands.md
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  evaluator/functions.go
  examples/background-command-exit.abs
  examples/background-command.abs
  object/object.go
Labels: enhancement
